language: node_js
node_js:
  - 10
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
jobs:
  include:
    - stage: Test
      node_js: 10
      script: 'jest --coverage --collectCoverageFrom=src/lib/**/*.js && cat ./coverage/lcov.info | coveralls'
    - stage: Release
      if: (NOT type IN (pull_request)) AND (branch = master)
      node_js: 10
      script: skip
      deploy:
        provider: script
        cleanup: false
        script: "npm run-script build && npx semantic-release"

