sudo: false
language: node_js
node_js:
  - 10
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: Produce Coverage
      node_js: 10
      script:
        - npm run-script test --coverage --collectCoverageFrom=src/lib/**/*.js --coverageReporters=text-lcov | coveralls
    - stage: release
      node_js: 10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "npm run-script build && npx semantic-release"

