sudo: false
language: node_js
node_js:
  - 10
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: Test
      node_js: 10
      script:
        - '[ "${TRAVIS_PULL_REQUEST}" = "true" ] && npm run-script test'
        - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && jest --coverage --collectCoverageFrom=src/lib/**/*.js && cat ./coverage/lcov.info | coveralls'
    - stage: Release
      node_js: 10
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: "npm run-script build && npx semantic-release"

